INSERT INTO
  ocorrencia(
    denunciante_id,
    endereco,
    referencia,
    cidade,
    estado,
    cep,
    data_ocorrencia,
    observacao
  )
VALUES
  (
    '__ID_DENUNCIANTE__',
    '__ENDERECO__',
    '__REFERENCIA__',
    '__CIDADE__',
    '__ESTADO__',
    '__CEP__',
    '__DATA_OCORRENCIA__',
    '__OBSERVACAO'
  );