INSERT INTO
  buraco(
    denunciante_id,
    endereco,
    referencia,
    cidade,
    estado,
    cep,
    data_ocorrencia,
    gravidade,
    tratado,
    observacao
  )
VALUES
  (
    '__DENUNCIANTE_ID',
    '__ENDERECO__',
    '__REFERENCIA__',
    '__CIDADE__',
    '__ESTADO__',
    '__CEP__',
    '__DATA_OCORRENCIA__',
    '__GRAVIDADE__',
    '__TRATADO__',
    '__OBSERVACAO__'
  );